### PR TITLE
Add documentation for android

### PR DESCRIPTION
**Pull request by ademar111190**
Add doc on how to use the SDK on Android

### CODE REVIEW

**Comment by JssDWt** [comment]
I think the docs are not the place for this? 
Did you mean to put this example in the https://github.com/breez/breez-sdk repo?

**Comment by ademar111190** [comment]
> I think the docs are not the place for this? Did you mean to put this example in the https://github.com/breez/breez-sdk repo?

@JssDWt  I moved the example to the SDK repo https://github.com/breez/breez-sdk/pull/386/files

**Comment by ok300** [comment]
Closing this, since the example was moved as per above https://github.com/breez/breez-sdk-docs/pull/32#issuecomment-1667757300 .

**Comment by ademar111190** [comment]
@JssDWt This PR is adding the android example in the doc.
I moved the android code example (an android project)

**Review by ok300 — APPROVED** [review]
LGTM

**Pull request merged**
