### PR TITLE
Reorg custom-tabs sections to remove duplication

### PR DESCRIPTION
**Pull request by ok300**
Apply the same reorg from #35 (which was done on only one doc file) to all documentation `md` files.

### CODE REVIEW

**Comment by ok300** [comment]
The simplest way to review is to run it locally

```
mdbook serve --open
```

and click through the available tabs.

On pages with more than one code block, each code block should have tabs with available languages.

**Review by JssDWt — APPROVED** [review]
Tested locally and clicked through all languages. It looks good!

**Comment by JssDWt** [comment]
There's this thing where the tabs are annoying on the fiat currencies page.
Probably we should add all language tabs there, but put nothing in the code, or a TODO in the code.

**Comment by ok300** [comment]
Done, added TODOs for now.

**Pull request merged**
