### PR TITLE
Update snippets with new connect() signature

### PR DESCRIPTION
**Pull request by ok300**
Updates snippets to reflect https://github.com/breez/breez-sdk/commit/4e43a42b9d4f6b200fa1f3f7b8f21ca145b31aaa

The relevant change for the snippets is the `ConnectRequest` arg in `sdk.connect()`.

### CODE REVIEW

**Comment by dangeross** [comment]
There is already a draft PR https://github.com/breez/breez-sdk-docs/pull/133  for this, but its out of date (and not well titled). Maybe you can pull the `restore_only` examples into your PR?

**Comment by ok300** [comment]
Thanks @dangeross , I cherry-picked it here and bumped the SDK to v0.3.1.

**Review by dangeross — COMMENTED** [review]
LGTM, but best to let @erdemyerebasmaz check. I guess it's due in v0.3.4

**Comment by erdemyerebasmaz** [comment]
> LGTM, but best to let @erdemyerebasmaz check. I guess it's due in v0.3.4

We expect to release C-Breez in a week & have entered testing stages. Aside from hotfix releases, I suspect the next feature release will be delayed by then in case we find things we should address ASAP on the SDK.

CC: @roeierez

**Review by erdemyerebasmaz — APPROVED** [review]
LGTM

**Pull request merged**
