### PR TITLE
C# Snippets indentation

### PR DESCRIPTION
**Pull request by erdemyerebasmaz**
Installed [EditorConfig for VS Code](https://github.com/editorconfig/editorconfig-vscode) and formatted with the settings on `.editorconfig` file.

### CODE REVIEW

**Comment by erdemyerebasmaz** [comment]
@JssDWt re: your question;
> Can we do something about the indentation of the code?

Do you wish to remove the indentation before all snippets?

CC: @ok300

**Comment by JssDWt** [comment]
> Do you wish to remove the indentation before all snippets, so the snippet itself is the zeroth-point for indentation?

Yeah that would be the best. I think two space indentation for C# looks a bit weird. Preferably keep the indentation to 4 spaces, but aline them om the left somehow.

**Comment by JssDWt** [comment]
@erdemyerebasmaz I have another option: https://github.com/breez/breez-sdk-docs/pull/80

**Comment by erdemyerebasmaz** [comment]
> @erdemyerebasmaz I have another option: #80

Closing in favor of aforementioned PR

**Pull request closed without merging**
