### PR TITLE
Extract code snippets and reference them from doc files

### PR DESCRIPTION
**Pull request by ok300**
This PR extracts the Rust snippets into a separate subproject. The docs then reference a line range from that subproject, which `mdBook` then renders as an embedded snippet.

IMO if we do this for every language, it will make it easier for us to maintain the doc snippets. All we have to do is: for every language, git checkout and compile. It also helps with refactoring (changes in arguments or return types, etc).

The tricky part is we have to be careful with the line ranges referenced in the `md` files. If we put all snippets in one big source code file per language, and reference ranges in there, then any change in that file could invalidate many other referenced line ranges. The simplest solution I found is to split the snippets in a `rs` file per `md` doc file. This way, if I have to change `some_method.md` then I know all I have to do is update the snippet in `some_method.rs` and re-check the line references for that one page.

What do you think? Is this worth trying out?

(Draft for now, because not sure if we want to do this or not.)

---

Snippet extracted to sub-project:

* [x] Rust
* [ ] Swift
* [ ] Kotlin
* [x] React Native
* [x] Dart
* [ ] Python
* [x] Go
* [x] C#

CI checks compilation on `main` and new PRs:

* [x] Rust
* [ ] Swift
* [ ] Kotlin
* [ ] React Native
* [x] Dart
* [ ] Python
* [ ] Go
* [x] C#

### CODE REVIEW

**Comment by dangeross** [comment]
It's a really nice idea and it keeps the md files clean. I think it's really valuable to be able to use valid code for the examples, I found lots of errors just by putting the examples into Replit. It would be nice to put some compilation checks into the CI of this repo to check the code is valid also.

**Comment by JssDWt** [comment]
I think this is great. This will help a lot.
I think it may even be beneficial to have these code snippets inside the sdk repo, so the documentation change becomes part of the code change.

Looks like we can also put anchors in the files to make them not so prone to breaking on changes when lines are changed. https://rust-lang.github.io/mdBook/format/mdbook.html

Also btw, this allows for formatting the code properly, we can even check for that in CI.

```
// ANCHOR: component
struct Paddle {
    hello: f32,
}
// ANCHOR_END: component
```

With
```
{{#include file.rs:component}}
```

**Comment by ok300** [comment]
I included @dangeross 's suggestion to have the CI check the code (in this case with `cargo clippy`).

I also included @JssDWt 's point about using code anchors instead of line ranges.

The PR is ready for review. The Rust snippets are now living in the `snippets/rust` subproject and referenced from the `md` files. The CI is making sure the code is valid on every PR.

**Comment by dangeross** [comment]
Looking really nice. So the intension is that all language snippets are compilable against the latest release, any ideas how we could test the snippets compiling against the main branch? So we could actively develop the snippets as development goes on in the sdk.

**Review by erdemyerebasmaz — COMMENTED** [review]
Looks really good!

I'm working on Dart snippets :) 

Here's my progress: [snippets_dart differences](https://github.com/breez/breez-sdk-docs/compare/ok300-snippets-rust...snippets_dart)

How can we reference the `.dart` files on mdbook? They seem to only work for `.rs` files.

**Comment by erdemyerebasmaz** [comment]
> Looking really nice. So the intension is that all language snippets are compilable against the latest release, any ideas how we could test the snippets compiling against the main branch? So we could actively develop the snippets as development goes on in the sdk.

For Dart, I've used the package that references main branch as dependency.

```
dependencies:
  breez_sdk:
    git:
      url: https://github.com/breez/breez-sdk-flutter
```


---

If the code snippets are compiled against breez-sdk@main during this process and once they are extracted for all languages, these changes as a whole would make
- #64 
- #66 
- #67 
- #68 

obsolete.

**Comment by ubbabeck** [comment]
Looks very good and much easier to maintain. Working on a pr for the python snippets.

**Comment by JssDWt** [comment]
@ok300  Maybe we should just merge this branch and add the remainder to main one by one?

**Comment by JssDWt** [comment]
We need a way to target a specific commit on `breez-sdk` with this setup. Currently we're taking the already published packages as input for the docs, but ideally the docs are ready before the code is released.

**Pull request merged**
