### PR TITLE
Fix Swift CI warnings

### PR DESCRIPTION
**Pull request by ok300**
~This PR bumps the SDK dependency of all snippets from 0.2.10  to 0.2.15.~

This PR fixes the Swift CI warnings
- see Swift warnings + errors before PR: https://github.com/breez/breez-sdk-docs/actions/runs/7726293683/job/21062288760
- see Swift same errors, but no warnings after PR: https://github.com/breez/breez-sdk-docs/actions/runs/7728266262/job/21068648940?pr=126

The remaining errors will be solved by a new published version of `breez-sdk-swift` as described [here](https://github.com/breez/breez-sdk-docs/pull/126#issuecomment-1912890227).

### CODE REVIEW

**Comment by ok300** [comment]
I'm not yet sure why the Swift CI is failing. The logs have warnings like

```
warning: object file ... was built for newer macOS version (13.0) than being linked (12.0)
```

which is probably because breez-sdk-swift [is built with macos-13](https://github.com/breez/breez-sdk-swift/blob/0a88fb63a3fb60da9f35e10228205178e3bd9a94/.github/workflows/publish-swift-package.yaml#L15) but the snippets [are using macos-12](https://github.com/breez/breez-sdk-docs/blob/89ab58f14e576255bf183062cf34c97fb3fe7c57/snippets/swift/BreezSDKExamples/Package.swift#L8).

But this hasn't changed since 0.2.10 so it can't be the reason it fails.

@dangeross @ubbabeck any idea what is missing for the Swift CI to pass?

**Comment by ok300** [comment]
I think the reason pointing to an SDK commit doesn't work for Swift, is because the 0.2.14 Swift bindings are downloaded and used:

```
Downloading binary artifact https://github.com/breez/breez-sdk-swift/releases/download/0.2.14/breez_sdkFFI.xcframework.zip
[15149/317738527] Downloading https://github.com/breez/breez-sdk-swift/releases/download/0.2.14/breez_sdkFFI.xcframework.zip
Downloaded https://github.com/breez/breez-sdk-swift/releases/download/0.2.14/breez_sdkFFI.xcframework.zip (22.30s)
```

So any changes in the SDK dependency tree is not reflected in the Swift bindings used by the CI here.

However I tried to run `swift build` locally, adjusting it to point to the local Swift bindings (generated with `make bindings-swift` on https://github.com/breez/breez-sdk/pull/757), as described by @ubbabeck in https://github.com/breez/breez-sdk-docs/pull/110/commits/20576b6edebfaf51672a33c949786c2d8f2db10f, and I got

```
...
[24/24] Linking BreezSDKDocs
Build complete! (3.11s)
```

So, unless I made any mistakes above, it looks like this CI step will only work after the next release, when `breez-sdk-swift` will contain binaries generated from a `breez-sdk` that includes https://github.com/breez/breez-sdk/pull/757.

**Comment by ok300** [comment]
The actual bumping to 0.2.15 already happened and was merged in `main` as part of a previous PR.

This PR only gets rid of a few warnings in Swift and updates the `pubspec.lock`.

**Review by JssDWt — APPROVED** [review]
LGTM

**Pull request merged**
